ALTER TABLE users ADD COLUMN IF NOT EXISTS fan VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS fayda_sub VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS fayda_verified_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS fayda_birthdate DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS fayda_gender VARCHAR(20);